apiVersion: v1
kind: Template
labels:
  template: image-mirror-secret
metadata:
  annotations:
    description: Cluster Credential Secret
    tags: secret
    version: 1.0.0
  name: image-mirror-secret
objects:
- apiVersion: v1
  stringData:
    username: generic
    password: "${TOKEN}"
  data:
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
    labels:
      credential.sync.jenkins.openshift.io: 'true'
  type: kubernetes.io/basic-auth
parameters:
- description: The name for the application.
  name: SECRET_NAME
  required: true
- description: Service Account Token
  name: TOKEN
  required: true