---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: promoter
    namespace: multicluster-spring-boot-prod
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: edit
    namespace: multicluster-spring-boot-prod
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: promoter
    namespace: multicluster-spring-boot-prod
  userNames:
  - system:serviceaccount:multicluster-spring-boot-prod:promoter
