kind: LimitRange    
apiVersion: v1
metadata:
    name: limits
    creationTimestamp: null
spec:
  limits:
  - max:
      cpu: 100m
      memory: 750Mi
    min:
      cpu: 10m
      memory: 5Mi
    type: Pod
  - default: 
      cpu: 50m
      memory: 100Mi
    max:
      cpu: 100m
      memory: 750Mi
    min:
      cpu: 10m
      memory: 5Mi
    type: Container
