apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "cicd-core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1500m" 
        memory: "7Gi" 

    - type: "Container"
      max:
        cpu: "1700m" 
        memory: "4Gi" 


