kind: LimitRange
apiVersion: v1
metadata:
  creationTimestamp: null
  name: app-limits
spec:
  limits:
  - max:
      cpu: 2000m
      memory: 4Gi
    min:
      cpu: 400m
      memory: 512Mi
    type: Pod
  - default:
      cpu: 600m
      memory: 1Gi
    max:
      cpu: 2000m
      memory: 4Gi
    min:
      cpu: 400m
      memory: 512Mi
    type: Container