apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2" 
        memory: "2Gi" 
      min:
        cpu: "1" 
        memory: "1Gi" 
    - type: "Container"
      max:
        cpu: "2" 
        memory: "2Gi" 
      min:
        cpu: "1" 
        memory: "4Mi" 
      default:
        cpu: "1" 
        memory: "1Gi" 
      defaultRequest:
#        cpu: "700m"
        cpu: "1" 
        memory: "1Gi" 
      maxLimitRequestRatio:
        cpu: "1" 
