apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "3" 
        memory: "3Gi" 
      min:
        cpu: "800m" 
        memory: "1280Mi" 
    - type: "Container"
      max:
        cpu: "2" 
        memory: "3Gi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
      default:
        cpu: "700m" 
        memory: "1280Mi" 
      defaultRequest:
        cpu: "700m" 
        memory: "1280Mi" 
      maxLimitRequestRatio:
        cpu: "10" 
